// Self-attack script: fires each of the 6 evaluation probes at a LIVE server and writes the
// real request/response output straight into EVIDENCE.md. Run with the server already up
// (ENABLE_TEST_CONTROLS=true) via `npm run attack`.
import { writeFileSync } from 'node:fs';

const BASE = process.env.ATTACK_BASE_URL ?? 'http://localhost:3000';
const CONTROL_TOKEN = process.env.CONTROL_TOKEN ?? process.env.ATTACK_CONTROL_TOKEN;
if (!CONTROL_TOKEN) { console.error('Set CONTROL_TOKEN (matching your .env) before running npm run attack.'); process.exit(1); }

const log = [];
const section = (title) => log.push(`\n## ${title}\n`);
const record = (label, reqLine, res, bodyText) => log.push(`**${label}**\n\n\`\`\`\n${reqLine}\n→ HTTP ${res.status}\n${bodyText}\n\`\`\`\n`);

async function req(method, path, { body, headers = {} } = {}) {
  const opts = { method, headers: { ...headers } };
  if (body !== undefined) { opts.headers['content-type'] ??= 'application/json'; opts.body = typeof body === 'string' ? body : JSON.stringify(body); }
  const res = await fetch(BASE + path, opts);
  const text = await res.text();
  return { res, text, reqLine: `${method} ${path}${headers.origin ? `  (Origin: ${headers.origin})` : ''}` };
}
const control = (path, body) => req('POST', `/__control${path}`, { body, headers: { 'x-control-token': CONTROL_TOKEN } });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function main() {
  log.push(`# EVIDENCE.md\n\nGenerated by \`npm run attack\` against a live server at \`${BASE}\` on ${new Date().toISOString()}.\nEvery block below is a real request/response pair captured by the script itself.\n`);

  const keyA = process.env.SEED_TENANT_A_API_KEY;
  const keyB = process.env.SEED_TENANT_B_API_KEY;
  if (!keyA || !keyB) { console.error('Set SEED_TENANT_A_API_KEY / SEED_TENANT_B_API_KEY (matching your .env) before running npm run attack.'); process.exit(1); }

  const { text: wText } = await req('POST', '/api/widgets', {
    body: { type: 'signup_form', title: 'Attack Target', fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }] },
    headers: { 'x-api-key': keyA },
  });
  const widget = JSON.parse(wText).widget;
  // A second, dedicated widget for probes 4-6, so the flood of requests in probe 3 can never
  // bury or interfere with the geo/email/honeypot evidence pulled from the dashboard later.
  const { text: w2Text } = await req('POST', '/api/widgets', {
    body: { type: 'signup_form', title: 'Attack Target (probes 4-6)', fields: [{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }] },
    headers: { 'x-api-key': keyA },
  });
  const widget2 = JSON.parse(w2Text).widget;
  await control('/reset', {});

  section('Requirement — Multi-tenant isolation');
  const r = await req('GET', `/api/widgets/${widget.id}`, { headers: { 'x-api-key': keyB } });
  record("Tenant B tries to read Tenant A's widget", r.reqLine, r.res, r.text);

  section('PROBE 1 — Valid cross-origin submission, stored, visible via dashboard');
  const p1 = await req('POST', `/widgets/${widget.publicId}/submissions`, { body: { name: 'Ada Lovelace', email: 'ada@example.com' }, headers: { origin: 'http://localhost:5500' } });
  record('POST /widgets/:id/submissions from a different origin', p1.reqLine, p1.res, p1.text);
  const list = await req('GET', `/api/widgets/${widget.id}`, { headers: { 'x-api-key': keyA } });
  record("Widget still owned by A (ownership check via GET)", list.reqLine, list.res, list.text.slice(0, 300) + '…');

  section('PROBE 2 — Malformed and oversized payloads');
  const malformed = await req('POST', `/widgets/${widget.publicId}/submissions`, { body: '{"name":', headers: { 'content-type': 'application/json' } });
  record('Malformed JSON', malformed.reqLine, malformed.res, malformed.text);
  const oversized = await req('POST', `/widgets/${widget.publicId}/submissions`, { body: { name: 'x'.repeat(20000), email: 'a@b.co' } });
  record('Oversized body (>10KB)', oversized.reqLine, oversized.res, oversized.text);

  section('PROBE 3 — Burst of rapid submissions -> 429s, service stays up');
  const burst = await Promise.all(Array.from({ length: 15 }, () => req('POST', `/widgets/${widget.publicId}/submissions`, { body: { name: 'Flood', email: 'flood@example.com' } })));
  const statuses = burst.map((b) => b.res.status);
  log.push(`**15 concurrent submissions from one IP**\n\n\`\`\`\nstatuses: ${JSON.stringify(statuses)}\n201 accepted: ${statuses.filter((s) => s === 201).length}\n429 rate-limited: ${statuses.filter((s) => s === 429).length}\n\`\`\`\n`);
  const health = await req('GET', '/health', {});
  record('Server health immediately after the burst', health.reqLine, health.res, health.text);
  await control('/reset', {}); // clear the budget the burst just spent, so it isn't collateral damage on later probes

  section('PROBE 4 — Geo enrichment fallback chain');
  const p4a = await req('POST', `/widgets/${widget2.publicId}/submissions`, { body: { name: 'Geo A', email: 'a@example.com' }, headers: { 'x-forwarded-for': '8.8.8.8' } });
  record('Provider A up -> submission enriched by ip-api', p4a.reqLine, p4a.res, p4a.text);
  await control('/faults', { 'ip-api': true });
  const p4b = await req('POST', `/widgets/${widget2.publicId}/submissions`, { body: { name: 'Geo B', email: 'b@example.com' }, headers: { 'x-forwarded-for': '8.8.8.8' } });
  record('Provider A (ip-api) down -> ipapi-co answers', p4b.reqLine, p4b.res, p4b.text);
  await control('/faults', { 'ip-api': true, 'ipapi-co': true });
  const p4c = await req('POST', `/widgets/${widget2.publicId}/submissions`, { body: { name: 'Geo None', email: 'c@example.com' }, headers: { 'x-forwarded-for': '8.8.8.8' } });
  record('BOTH providers down -> submission still succeeds (no geo)', p4c.reqLine, p4c.res, p4c.text);
  await control('/reset', {});
  const dash4 = await req('GET', `/api/widgets/${widget2.id}/submissions?limit=3`, { headers: { 'x-api-key': keyA } });
  record('Dashboard confirms WHICH provider actually answered each one (newest first: none, ipapi-co, ip-api)', dash4.reqLine, dash4.res, dash4.text);

  section('PROBE 5 — Email side effect throws; submission still succeeds');
  await control('/faults', { email: true });
  const p5 = await req('POST', `/widgets/${widget2.publicId}/submissions`, { body: { name: 'Email Down', email: 'edown@example.com' }, headers: { 'x-forwarded-for': '8.8.8.8' } });
  record('Email provider forced down -> submission still 2xx', p5.reqLine, p5.res, p5.text);
  // Poll (rather than a fixed sleep) until the two jobs this submission just queued actually
  // reach a terminal state, so the evidence shows the real dead-letter outcome, not a mid-retry snapshot.
  let stateText = '';
  for (let i = 0; i < 40; i++) {
    await sleep(500);
    const s = await req('GET', '/__control/state', { headers: { 'x-control-token': CONTROL_TOKEN } });
    stateText = s.text;
    const parsed = JSON.parse(s.text);
    const stillWorking = parsed.jobs.recent.filter((j) => ['send_confirmation_email', 'notify_owner'].includes(j.type) && j.status === 'running');
    const relevant = parsed.jobs.recent.filter((j) => j.last_error?.includes('forced failure'));
    if (relevant.length >= 2 && relevant.every((j) => j.status === 'dead') && stillWorking.length === 0) break;
  }
  record('Job queue state after polling to completion: both jobs dead-lettered at max_attempts, submission was unaffected throughout', 'GET /__control/state (polled until terminal)', { status: 200 }, stateText);
  await control('/reset', {});

  section('PROBE 6 — Honeypot field filled like a bot would');
  const before6 = await req('GET', `/api/widgets/${widget2.id}/submissions?limit=100`, { headers: { 'x-api-key': keyA } });
  const beforeCount = JSON.parse(before6.text).submissions.length;
  const p6 = await req('POST', `/widgets/${widget2.publicId}/submissions`, { body: { name: 'Bot', email: 'bot@example.com', website: 'http://spam.example' } });
  record('Honeypot filled -> looks like success to the bot, nothing new stored', p6.reqLine, p6.res, p6.text);
  const after6 = await req('GET', `/api/widgets/${widget2.id}/submissions?limit=100`, { headers: { 'x-api-key': keyA } });
  const afterCount = JSON.parse(after6.text).submissions.length;
  log.push(`**Confirming the bot's row was never actually written**\n\n\`\`\`\nsubmission count before: ${beforeCount}\nsubmission count after:  ${afterCount}\nunchanged: ${beforeCount === afterCount}\n\`\`\`\n`);

  writeFileSync('EVIDENCE.md', log.join('\n'));
  console.log(`\nWrote EVIDENCE.md (${log.length} sections) from live attack output.`);
}
main().catch((err) => { console.error('attack script failed:', err); process.exit(1); });
